# Generated by Django 2.2.19 on 2021-09-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weather',
            new_name='Record',
        ),
    ]
