# Generated by Django 2.2.19 on 2021-09-07 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210907_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Summaries'},
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Weather Records'},
        ),
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
