# Generated by Django 2.2.19 on 2021-09-07 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20210908_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='avg_temperature',
            new_name='avg_temp',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature',
        ),
        migrations.AddField(
            model_name='weather',
            name='temp',
            field=models.FloatField(default=25, validators=[django.core.validators.MinValueValidator(19.0), django.core.validators.MaxValueValidator(28.0)], verbose_name='Temperature'),
            preserve_default=False,
        ),
    ]
