# Generated by Django 2.2.19 on 2021-09-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20210908_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='summary_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
